---
title: "Lab3"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse) #Standard data analysis package
library(sf) #Allows for the opening and analysis of spatial files 
library(leaflet) #Important for building interactive tmap tools
library(tmap) #Allows for building interactive HTML tools 
#library(maptools) #Allows for more advanced map manipulating and other geospatial tools
library(sp) #Allows for manipulating spatial datasets as type Spatial, which is necissary for some wrangling not shown here
library(raster) #Reads in raster data and has some analysis tools
#library(beepr) #Useful for long loading times
library(RColorBrewer)
```

```{r}
SB_tracts <- st_read(dsn = ".", layer = "tl_2010_06083_tract00") %>% 
   st_transform(crs = 4326)%>% 
  mutate(CTIDFP00 = as.numeric(CTIDFP00)) %>% 
  mutate(Id2 = paste(STATEFP00, COUNTYFP00, TRACTCE00, sep = "")) %>% 
  mutate(Id2 = as.numeric(Id2))
  
census_data_2010 = read_csv("DEC_10_SF1_P1_with_ann.csv") %>% 
  mutate(CTIDFP00 = Id2) %>% 
  mutate(Total2010 = Total)
census_data_2000 = read_csv("DEC_00_SF1_H010_with_ann.csv") %>% 
  mutate(CTIDFP00 = Id2) %>% 
  mutate(Total2000 = Total)

```


```{r}
plot(SB_tracts)
```

```{r}
census_map_2010 = full_join(SB_tracts, census_data_2010,census_data_2000, by = "Id2")

census_pop_change = full_join(census_map_2010, census_data_2000, by = "Id2") %>% 
  filter(!is.na(Total2000)) %>% 
  filter(!is.na(Total2010)) %>% 
  dplyr::select(Total2000,Total2010) %>% 
  mutate(difference=Total2010-Total2000)

#plot(census_map)
```


```{r}
ggplot(census_pop_change)+
  geom_sf(aes(fill = difference))+
  scale_fill_gradient2("Value Discrepency",low = "firebrick4", mid = "white", high = "deepskyblue4", breaks=c(min(census_pop_change$difference),0,max(census_pop_change$difference)),labels=c("-520","0","4700"))+
  labs(x = "", y = "", title = "Comparitive Urban Heat Island of Census \nTracts Based off Land Surface Temperature")+
  theme_minimal()+
  coord_sf(datum=NA)
```

```{r}
st_write(census_pop_change, "populationchange.shp", driver="ESRI Shapefile") 
```

