---
title: "WaterQuality"
author: "Madeline Gorchels"
date: "10/30/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(tidyverse)
library(janitor)
library(stringr)
library(tidyverse)
library(sf)
library(tmap)
library(leaflet)
library(ggrepel)
library(ggspatial)
library(RColorBrewer)
library(raster)
```

```{r}
monitoring = read_csv("narrowresult.csv") %>% 
  clean_names() %>% 
  select(activity_start_date, monitoring_location_identifier, characteristic_name, result_measure_value, result_measure_measure_unit_code) %>% 
  mutate(Date=activity_start_date) %>% 
  mutate(ID = monitoring_location_identifier) %>% 
  mutate(Parameter = characteristic_name) %>% 
  mutate(Value = result_measure_value) %>% 
  mutate(Unit = result_measure_measure_unit_code) #%>% 
  select(Date, ID, Parameter, Value, Unit) %>% 
  filter(!is.na(Value))

siteinfo = read_csv("siteinfo.csv") %>% 
  clean_names()
```

```{r}
filtered_monitoring = monitoring %>% 
  filter(Parameter == "Nitrate"|Parameter=="Mercury"|Parameter=="Total dissolved solids"|Parameter=="Soduim"|Parameter== "Ammonia")
            #Count = count(Parameter))

site_filter = siteinfo %>% 
  mutate(ID=monitoring_location_identifier) %>% 
  mutate(Location=monitoring_location_name) %>% 
  mutate(WaterBody=monitoring_location_name) %>% 
  mutate(Latitude=latitude_measure) %>% 
  mutate(Longitude=longitude_measure) %>% 
  select(ID, Location, WaterBody, Latitude, Longitude)

site_sum = read_csv("SiteInfoFiltered.csv") %>% 
  rename(Organization=X7)

site_cont_sum=full_join(site_sum,filtered_monitoring, by = "ID") %>% 
  group_by(Organization,ID,Parameter)%>% 
  summarise(min=min(Date),
            max=max(Date)) %>% 
  filter(!is.na(Parameter))

write.csv(site_cont_sum, file="SiteFull.csv")
```

```{r}
#write.csv(filtered_monitoring, file="Filtered_MonitoringData.csv")
#write.csv(site_filter, file="SiteInfoFiltered.csv")
```

Creating map with the stations on it 

```{r}
stations = read_sf(dsn = "WQstations", layer = "WaterQuality_MonitoringSites") %>% 
  mutate(ID=SiteInfo_1)
```

```{r}
plot(stations)

stations_org= full_join(stations,site_cont_sum, by="ID")
#st_write(stations_org, "stations_org.shp", driver="ESRI Shapefile") 
```

